source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'passport'
gem 'devise'
gem 'nifty-generators'
gem 'omniauth'       
gem 'mysql'  
gem 'prawn'
gem 'fb_graph'
gem 'will_paginate', '3.0.pre2'
gem 'jquery-rails' 
gem 'cocaine'
gem 'aws-s3'
gem 'ajaxful_rating', '3.0.0.beta3'   
gem  'rhoconnect-rb'

