source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'passport'
gem 'devise'
gem 'nifty-generators'
gem 'omniauth'
gem 'mongrel', '1.2.0.pre2'       
gem 'mysql'  
gem 'prawn'
gem 'fb_graph'
gem 'will_paginate', '3.0.pre2'
gem 'jquery-rails'
