development:
     host: localhost
     adapter: mysql
     database: kh
     port: 3306
     username: root
     password: 

test: &test
     host: localhost
     adapter: mysql
     database: kh_test
     port: 3306
     username: root
     password: 

production:
     host: localhost
     adapter: mysql
     database: kh
     port: 3306
     username: root
     password: 
