common: &common
    access_key_id: AKIAIWWQF5REKTC4ZYGQ
    secret_access_key: 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

development:
    <<: *common
    bucket: Khmobile

test:
    <<: *common
    bucket: Khmobile-123-test

production:
    <<: *common
    bucket: Khmobile